parameters:
  - name: jobName
    type: string
    default: BicepLintCode
  - name: dependsOn
    type: object
    default: []
  - name: azureSubscription
    type: string
  - name: bicepDirectory
    type: string
    default: "$(Build.sourcesDirectory)/bicep"

jobs:
  - job: ${{ parameters.jobName }}
    dependsOn: ${{ parameters.dependsOn }}
    pool:
      vmImage: ubuntu-latest

    workspace:
      clean: all

    steps:
      - task: AzureCLI@2
        name: RunBicepBuild
        inputs:
          azureSubscription: ${{ parameters.azureSubscription }}
          scriptType: "pscore"
          scriptLocation: "inlineScript"
          inlineScript: |
            $files = Get-ChildItem '${{ parameters.bicepDirectory }}/*.bicep' -Recurse
            foreach ($file in $files) {
              Write-Host "Running az bicep restore and build for '$($file.FullName)'"
              bicep restore $file.FullName --force
              bicep build $file.FullName
            }
