parameters:
- name: jobName
  type: string
  default: 'BuildNetCoreProjects'
- name: buildConfiguration
  type: string
  default: 'Release'
- name: projects
  type: string
  default: '**/*.csproj'
- name: projectsTests
  type: string
  default: '**/*.Tests.csproj'
- name: nugetConfigPath
  type: string
  default: ''
- name: dotnetSdkVersion
  type: string
  default: '6.x'
  
jobs:
- job: ${{ parameters.jobName }}

  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET SDK ${{ parameters.dotnetSdkVersion }}'
    inputs:
      version: ${{ parameters.dotnetSdkVersion }}

  - task: DotNetCoreCLI@2
    displayName: 'Restore project dependencies'
    inputs:
      command: 'restore'
      projects: ${{ parameters.projects }}

  - task: DotNetCoreCLI@2
    displayName: 'Build the projects - ${{ parameters.projects }} - ${{ parameters.buildConfiguration }}'
    inputs:
      command: 'build'
      arguments: '--no-restore --configuration ${{ parameters.buildConfiguration }}'
      projects: ${{ parameters.projects }}

  - task: DotNetCoreCLI@2
    displayName: 'Run unit tests - ${{ parameters.projects }} - ${{ parameters.buildConfiguration }}'
    inputs:
      command: 'test'
      arguments: '--no-build --configuration ${{ parameters.buildConfiguration }}'
      publishTestResults: true
      projects: ${{ parameters.projectsTests }}
