parameters:
- name: jobName
  type: string
  default: 'BuildNetCoreProjects'
- name: buildConfiguration
  type: string
  default: 'Release'
- name: projects
  type: string
  default: '**/*.csproj'
- name: projectsTests
  type: string
  default: '**/*.Tests.csproj'
- name: nugetConfigPath
  type: string
  default: ''
- name: dotnetSdkVersion
  type: string
  default: '6.x'
- name: toolsManifestPath
  type: string
  default: ''
- name: useCobertura
  default: false
  type: boolean
- name: additionalBuildSteps
  type: stepList
  default: []
- name: additionalPublishSteps
  type: stepList
  default: []

jobs:
- job: ${{ parameters.jobName }}

  workspace:
    clean: all

  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET SDK ${{ parameters.dotnetSdkVersion }}'
    inputs:
      version: ${{ parameters.dotnetSdkVersion }}

  - task: DotNetCoreCLI@2
    displayName: 'Restore project dependencies'
    inputs:
      command: 'restore'
      projects: ${{ parameters.projects }}

  - task: DotNetCoreCLI@2
    displayName: 'Build the projects - ${{ parameters.projects }} - ${{ parameters.buildConfiguration }}'
    inputs:
      command: 'build'
      arguments: '--no-restore --configuration ${{ parameters.buildConfiguration }}'
      projects: ${{ parameters.projects }}

  - ${{ each step in parameters.additionalBuildSteps }}:
    - ${{ step }}

  - task: DotNetCoreCLI@2
    condition: and(succeeded(), ne('${{ parameters.toolsManifestPath }}', ''))
    displayName: 'Install .NET tools from local manifest'
    inputs:
      command: custom
      custom: tool
      arguments: 'restore --tool-manifest ${{ parameters.toolsManifestPath }}'

  - task: DotNetCoreCLI@2
    condition: and(succeeded(), eq('${{ parameters.useCobertura }}', 'false'))
    displayName: 'Run unit tests - ${{ parameters.projectsTests }}'
    inputs:
      command: 'test'
      arguments: '--no-build --configuration ${{ parameters.buildConfiguration }}'
      publishTestResults: true
      projects: ${{ parameters.projectsTests }}

  - task: DotNetCoreCLI@2
    condition: and(succeeded(), eq('${{ parameters.useCobertura }}', 'true'))
    displayName: 'Run unit tests with code coverage - ${{ parameters.projectsTests }}'
    inputs:
      command: 'test'
      arguments: '--no-build --configuration ${{ parameters.buildConfiguration }} /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
      publishTestResults: true
      projects: ${{ parameters.projectsTests }}

  - task: DotNetCoreCLI@2
    condition: and(succeeded(), eq('${{ parameters.useCobertura }}', 'true'))
    displayName: 'Create code coverage report'
    inputs:
      command: custom
      custom: tool
      arguments: 'run reportgenerator -reports:$(Build.SourcesDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:HtmlInline_AzurePipelines'

  - task: PublishCodeCoverageResults@1
    condition: and(succeeded(), eq('${{ parameters.useCobertura }}', 'true'))
    displayName: 'Publish code coverage report'
    inputs:
      codeCoverageTool: 'cobertura'
      summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'

  - ${{ each step in parameters.additionalPublishSteps }}:
    - ${{ step }}
