parameters:
- name: jobName
  type: string
  default: PushNuGetPackages
- name: dependsOn
  type: object
  default: []
- name: variableGroupName
  type: string
  default: 'NuGet.org'
- name: artifactName
  type: string
  default: 'library'

jobs:
- job: ${{ parameters.jobName }}
  dependsOn: ${{ parameters.dependsOn }}

  workspace:
    clean: all

  variables:
  - group: ${{ parameters.variableGroupName }}

  steps:
    - download: current
      displayName: 'Download ${{ parameters.artifactName }} artifact'
      artifact: ${{ parameters.artifactName }}

    - pwsh: |
        Get-ChildItem '$(Pipeline.Workspace)/${{ parameters.artifactName }}/*.nupkg' | ForEach-Object {
          dotnet nuget push $_.FullName -s https://api.nuget.org/v3/index.json -k $(NUGET-PUSH-KEY-1)
        }