parameters:
- name: projectName
- name: workingDirectory

stages:
- stage: build
  jobs:
  - job: build
    pool:
      vmImage: 'windows-latest'

    steps:
    - task: DotNetCoreCLI@2
      displayName: Build ${{ parameters.projectName }}
      inputs:
        command: 'build'
        projects: |
          ${{ parameters.workingDirectory }}/${{ parameters.projectName }}.csproj
        arguments: --output $(System.DefaultWorkingDirectory)/${{ parameters.projectName }}_output --configuration Release

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/${{ parameters.projectName }}_output'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/${{ parameters.projectName }}_$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/${{ parameters.projectName }}_$(Build.BuildId).zip
      artifact: drop