parameters:
- name: workingDirectory
- name: backendServiceArm
- name: backendAzureRmResourceGroupName
- name: backendAzureRmStorageAccountName
- name: backendAzureRmContainerName
- name: backendAzureRmKey
- name: environmentServiceNameAzureRM
- name: varFile

stages:
- stage: DeployTerraform

  variables:
    commandOptions: '-var-file="${{ parameters.varFile }}"'

  jobs:
  - job: DeployTerraform
    steps:
      - task: TerraformInstaller@0
        displayName: 'Terraform: Install'
        inputs:
          terraformVersion: '1.0.7'

      - task: TerraformTaskV2@2
        displayName: 'Terraform: Init'
        inputs:
          workingDirectory: '${{ parameters.workingDirectory }}'
          backendServiceArm: '${{ parameters.backendServiceArm }}'
          backendAzureRmResourceGroupName: '${{ parameters.backendAzureRmResourceGroupName }}'
          backendAzureRmStorageAccountName: '${{ parameters.backendAzureRmStorageAccountName }}'
          backendAzureRmContainerName: '${{ parameters.backendAzureRmContainerName }}'
          backendAzureRmKey: '${{ parameters.backendAzureRmKey }}'

      - task: TerraformTaskV2@2
        displayName: 'Terraform: Validate'
        inputs:
          command: validate
          workingDirectory: '${{ parameters.workingDirectory }}'
          environmentServiceNameAzureRM: '${{ parameters.environmentServiceNameAzureRM }}'

      - task: TerraformTaskV2@2
        displayName: 'Terraform: Plan'
        inputs:
          command: plan
          workingDirectory: '${{ parameters.workingDirectory }}'
          commandOptions: '$(commandOptions)'
          environmentServiceNameAzureRM: '${{ parameters.environmentServiceNameAzureRM }}'

      - task: TerraformTaskV2@2
        displayName: 'Terraform: Apply'
        name: 'terraform_apply'
        inputs:
          command: apply
          workingDirectory: '${{ parameters.workingDirectory }}'
          commandOptions: '$(commandOptions)'
          environmentServiceNameAzureRM: '${{ parameters.environmentServiceNameAzureRM }}'

      - powershell: |
          $terraformOutput = Get-Content "$(terraform_apply.jsonOutputVariablesPath)" | ConvertFrom-Json
          $terraformOutput | Get-Member -MemberType NoteProperty | % { $o = $terraformOutput.($_.Name); Write-Host "##vso[task.setvariable variable=$($_.Name);isoutput=true;issecret=$($o.sensitive)]$($o.value)" }
        name: terraform_output
        displayName: 'Read terraform output vars'